spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            assertingparty:
              metadata-uri: https://dev-66074169.okta.com/app/exkllslp41Xf0XJ7K5d7/sso/saml/metadata
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"
          auth0:
            assertingparty:
              metadata-uri: https://dev-zk7cudsl1ernnsc2.us.auth0.com/u/login?state=https://dev-zk7cudsl1ernnsc2.us.auth0.com/samlp/metadata/AKHuOSsgG5MAVJedC3lV8MWQiIarFJ4d
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"